# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.0.4
_src_path: gh:algorandfoundation/algokit-react-frontend-template
author_email: 114148836+meetmthosar@users.noreply.github.com
author_name: meetmthosar
cloud_provider: none
preset_name: production
project_name: participation_token-frontend

